export const Action ={
    ALLDATA: 'ALLDATA',
    AdminData: 'ADMINDATA',
    CART : 'CART',
    UPDATE_QUANTITY : "UPDATE_QUANTITY",
    INCREMENT_QUANTITY : "INCREMENT_QUANTITY",
    DECREMENT_QUANTITY: "DECREMENT_QUANTITY"
}